version: '3'

services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 11111111
      MINIO_ACCESS_KEY: 11111111
      MINIO_SECRET_KEY: 11111111
    volumes:
      - /share/minio-data:/data
    ports:
      - "9000:9000"
    command: server /data --console-address ":9999"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
    